### PR TITLE
Fix issue "blockColorblindContent" is showing and taking up space on …

### PR DESCRIPTION
**Pull request by catscarlet**
Try to fix issue:"blockColorblindContent" is showing and taking up space on some websites #5

### CODE REVIEW

**Comment by Remzi1993** [comment]
@LeonardoCardoso This is clearly not working. Maybe you could try my fix or do something like:

`document.getElementById( 'blockColorblindContent' ).style.display = 'none';`

**Comment by catscarlet** [comment]
@Remzi1993

The element already has style {display: none} when created in version 1.5
What's the version are you using?

**Comment by Remzi1993** [comment]
@catscarlet I'm the using the version from the Chrome web store: https://chrome.google.com/webstore/detail/colorblinding/dgbgleaofjainknadoffbjkclicbbgaa?hl=en

I think it needs to be updated. because I don't see this.

**Comment by catscarlet** [comment]
@Remzi1993 Well unfortunately the one on Chrome web store is a 4 years old version.

Version 1.5 was released 7 months ago and already fixed this issue, but never published on Chrome web store.

Should check the version before try to fix it.

You can try and use version 1.5 if you know how to load extension manually.

**Comment by Remzi1993** [comment]
@catscarlet Could someone update the Chrome web store extension? I think @LeonardoCardoso needs to do it, because a lot of people are having this issue and it's his extension.

**Pull request merged**
